import { createFileRoute } from "@tanstack/react-router";
import { Edit3, PackageOpen, X } from "lucide-react";
import { useState } from "react";
import { Button } from "@/components/ui/button";
import { PageHeader, StatusBadge } from "@/components/payla";
import raquette from "@/assets/raquette-padel.jpg";
import balles from "@/assets/balles-tennis.jpg";
import gourde from "@/assets/gourde-sport.jpg";

export const Route = createFileRoute("/boutique")({ head: () => ({ meta: [{ title: "Boutique — Paylà" }, { name: "description", content: "Commandes et catalogue marchand Paylà." }, { property: "og:title", content: "Boutique — Paylà" }, { property: "og:description", content: "Gérez vos commandes et vos produits." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" }] }), component: ShopPage });
const orders=[['#1048','Imane Cherkaoui','1 290,00 MAD','Payée','À récupérer'],['#1047','Rachid Berrada','240,00 MAD','Échouée','—'],['#1046','Mehdi Lamrani','240,00 MAD','Payée','À récupérer'],['#1043','Sara Idrissi','390,00 MAD','Payée','Récupérée']];
const products=[{name:'Raquette Padel Pro',price:'1 290,00 MAD',stock:'8 en stock',image:raquette},{name:'Tube de 3 balles',price:'120,00 MAD',stock:'24 en stock',image:balles},{name:'Gourde isotherme',price:'190,00 MAD',stock:'12 en stock',image:gourde}];
function ShopPage(){const[tab,setTab]=useState<'Commandes'|'Catalogue'>('Commandes');const[edit,setEdit]=useState<(typeof products)[number]|null>(null);return <div className="mx-auto max-w-6xl px-4 py-6 sm:px-6 lg:px-8 lg:py-8"><PageHeader eyebrow="Ventes" title="Boutique" action={<div className="grid h-10 w-10 place-items-center rounded-lg bg-secondary text-primary"><PackageOpen className="h-5 w-5"/></div>}/><div className="mt-6 flex gap-1 rounded-lg bg-secondary p-1">{(['Commandes','Catalogue'] as const).map(x=><Button key={x} variant={tab===x?'default':'ghost'} className="flex-1" onClick={()=>setTab(x)}>{x}</Button>)}</div>
{tab==='Commandes'?<div className="mt-5 overflow-hidden rounded-xl bg-card shadow-card">{orders.map((o)=><div key={o[0]} className="grid grid-cols-[minmax(0,1fr)_auto] gap-3 border-b border-border/60 p-4 last:border-0"><div className="min-w-0"><p className="text-sm font-bold">Commande {o[0]}</p><p className="mt-1 truncate text-sm text-muted-foreground">{o[1]}</p><div className="mt-3 flex gap-2"><StatusBadge tone={o[3]==='Payée'?'green':'red'}>{o[3]}</StatusBadge>{o[4]!=='—'&&<StatusBadge tone={o[4]==='Récupérée'?'gray':'orange'}>{o[4]}</StatusBadge>}</div></div><p className="text-right text-base font-bold">{o[2]}</p></div>)}</div>:
<div className="mt-5 grid grid-cols-2 gap-3 lg:grid-cols-3">{products.map(p=><article key={p.name} className="overflow-hidden rounded-xl bg-card shadow-card"><img src={p.image} alt={p.name} loading="lazy" width={816} height={816} className="aspect-square w-full object-cover"/><div className="p-4"><p className="text-sm font-semibold">{p.name}</p><p className="mt-2 text-lg font-bold">{p.price}</p><div className="mt-1 flex items-center justify-between"><span className="text-xs text-success">{p.stock}</span><Button variant="ghost" size="icon" onClick={()=>setEdit(p)} aria-label={`Modifier ${p.name}`}><Edit3 className="h-4 w-4"/></Button></div></div></article>)}</div>}
{edit&&<div className="fixed inset-0 z-50 grid place-items-end bg-overlay sm:place-items-center"><form className="w-full rounded-t-xl bg-card p-5 sm:max-w-md sm:rounded-xl" onSubmit={e=>{e.preventDefault();setEdit(null)}}><div className="flex items-center justify-between"><h2 className="text-xl font-bold">Modifier le produit</h2><Button type="button" variant="ghost" size="icon" onClick={()=>setEdit(null)}><X className="h-5 w-5"/></Button></div><label className="mt-5 block text-sm font-medium">Nom<input defaultValue={edit.name} className="mt-2 h-11 w-full rounded-lg bg-secondary px-3"/></label><label className="mt-4 block text-sm font-medium">Prix en MAD<input defaultValue={edit.price.replace(' MAD','')} className="mt-2 h-11 w-full rounded-lg bg-secondary px-3"/></label><label className="mt-4 block text-sm font-medium">Stock<input defaultValue={edit.stock.split(' ')[0]} className="mt-2 h-11 w-full rounded-lg bg-secondary px-3"/></label><Button type="submit" size="lg" className="mt-6 w-full">Enregistrer</Button></form></div>}</div>}
