import { createFileRoute } from "@tanstack/react-router";
import { Building2, CheckCircle2, ChevronRight, Landmark, LockKeyhole, Mail, ShieldCheck, UserPlus } from "lucide-react";
import { useState } from "react";
import { Button } from "@/components/ui/button";
import { PageHeader, StatusBadge } from "@/components/payla";

export const Route=createFileRoute('/compte')({head:()=>({meta:[{title:'Compte — Paylà'},{name:'description',content:'Profil, validation, versements et équipe Paylà.'},{property:'og:title',content:'Compte — Paylà'},{property:'og:description',content:'Gérez votre entreprise, vos versements et les accès équipe.'},{property:'og:type',content:'website'},{name:'twitter:card',content:'summary_large_image'}]}),component:AccountPage});
function AccountPage(){const[invite,setInvite]=useState(false);const[saved,setSaved]=useState(false);return <div className="mx-auto max-w-5xl px-4 py-6 sm:px-6 lg:px-8 lg:py-8"><PageHeader eyebrow="Paramètres" title="Compte" action={<div className="grid h-10 w-10 place-items-center rounded-full bg-primary text-sm font-bold text-primary-foreground">YA</div>}/>
<div className="mt-6 grid gap-5 lg:grid-cols-2"><section className="rounded-xl bg-card p-5 shadow-card"><div className="flex items-start justify-between gap-3"><div className="flex gap-3"><div className="grid h-11 w-11 shrink-0 place-items-center rounded-lg bg-secondary text-primary"><Building2 className="h-5 w-5"/></div><div><h2 className="font-bold">Atlas Sports SARL</h2><p className="mt-1 text-sm text-muted-foreground">ICE 003124987000037</p></div></div><StatusBadge tone="green">Vérifié</StatusBadge></div><div className="mt-5 flex items-center gap-2 rounded-lg bg-success-soft p-3 text-sm text-success"><CheckCircle2 className="h-4 w-4"/>Identité et entreprise vérifiées</div><Button variant="outline" className="mt-5 w-full">Modifier les informations</Button></section>
<section className="rounded-xl bg-card p-5 shadow-card"><div className="flex items-center gap-3"><div className="grid h-11 w-11 place-items-center rounded-lg bg-secondary text-primary"><ShieldCheck className="h-5 w-5"/></div><div><p className="text-xs text-muted-foreground">Taux de commission appliqué</p><p className="mt-1 text-3xl font-bold">2,50 %</p></div></div><p className="mt-5 text-sm text-muted-foreground">Ce taux est appliqué à chaque transaction réussie et ne peut pas être modifié ici.</p></section>
<section className="rounded-xl bg-card p-5 shadow-card lg:col-span-2"><div className="flex items-center gap-3"><Landmark className="h-5 w-5 text-primary"/><h2 className="font-bold">Versement automatique</h2></div><div className="mt-5 grid gap-4 sm:grid-cols-3"><Field label="Fréquence" value="Chaque lundi"/><Field label="Compte bancaire" value="RIB •••• 4821"/><Field label="Seuil minimum" value="1 000,00 MAD"/></div><Button variant="outline" className="mt-5" onClick={()=>setSaved(true)}>Modifier</Button>{saved&&<span className="ml-3 text-sm text-success">Configuration enregistrée</span>}</section>
<section className="rounded-xl bg-card p-5 shadow-card lg:col-span-2"><div className="grid grid-cols-[minmax(0,1fr)_auto] items-center gap-4"><div><h2 className="font-bold">Accès équipe</h2><p className="mt-1 text-sm text-muted-foreground">2 collaborateurs actifs</p></div><Button size="sm" onClick={()=>setInvite(!invite)}><UserPlus className="h-4 w-4"/>Inviter</Button></div>{invite&&<form className="mt-5 grid gap-3 rounded-lg bg-secondary p-4 sm:grid-cols-[minmax(0,1fr)_auto]"><input type="email" required placeholder="collaborateur@entreprise.ma" className="h-10 min-w-0 rounded-lg bg-card px-3 text-sm outline-none ring-ring focus:ring-2"/><Button type="submit">Envoyer</Button><label className="flex items-center gap-2 text-xs text-muted-foreground sm:col-span-2"><input type="checkbox"/>Autoriser la gestion des remboursements</label></form>}<div className="mt-5 divide-y divide-border/60">{[['Yassine Amrani','Propriétaire','ya'],['Nadia El Mansouri','Réservations uniquement','na']].map((u,i)=><div key={u[0]} className="grid grid-cols-[auto_minmax(0,1fr)_auto] items-center gap-3 py-3"><div className="grid h-9 w-9 place-items-center rounded-full bg-secondary text-xs font-bold uppercase">{u[2]}</div><div className="min-w-0"><p className="truncate text-sm font-semibold">{u[0]}</p><p className="truncate text-xs text-muted-foreground">{u[1]}</p></div>{i===0?<LockKeyhole className="h-4 w-4 text-muted-foreground"/>:<ChevronRight className="h-4 w-4 text-muted-foreground"/>}</div>)}</div></section>
<section className="rounded-xl bg-card p-5 shadow-card lg:col-span-2"><div className="flex items-center gap-3"><Mail className="h-5 w-5 text-primary"/><div><h2 className="font-bold">Assistance Paylà</h2><p className="mt-1 text-sm text-muted-foreground">Réponse habituelle en moins de 2 heures.</p></div></div></section></div></div>}
function Field({label,value}:{label:string;value:string}){return <div className="rounded-lg bg-secondary p-4"><p className="text-xs text-muted-foreground">{label}</p><p className="mt-2 text-sm font-semibold">{value}</p></div>}
