import { createFileRoute } from "@tanstack/react-router";
import { Download, MoreHorizontal, Send, WalletCards } from "lucide-react";
import { useState } from "react";
import { Button } from "@/components/ui/button";
import { PageHeader, StatusBadge } from "@/components/payla";

export const Route=createFileRoute('/finances')({head:()=>({meta:[{title:'Finances — Paylà'},{name:'description',content:'Revenus, commissions, versements et liens de paiement Paylà.'},{property:'og:title',content:'Finances — Paylà'},{property:'og:description',content:'Une vue claire de vos revenus, commissions et versements.'},{property:'og:type',content:'website'},{name:'twitter:card',content:'summary_large_image'}]}),component:FinancePage});
const periods=['Aujourd’hui','Semaine','Mois','Personnalisé']; const source=['Tout','Réservation','Boutique','Lien de paiement'];
function FinancePage(){const[period,setPeriod]=useState('Mois');const[filter,setFilter]=useState('Tout');const[notice,setNotice]=useState('');return <div className="mx-auto max-w-6xl px-4 py-6 sm:px-6 lg:px-8 lg:py-8"><PageHeader eyebrow="Vue financière" title="Finances" action={<Button variant="outline" size="icon" aria-label="Exporter le relevé" onClick={()=>setNotice('Relevé CSV préparé')}><Download className="h-4 w-4"/></Button>}/>
<div className="mt-6 flex gap-2 overflow-x-auto pb-1">{periods.map(x=><Button key={x} size="sm" variant={period===x?'default':'outline'} onClick={()=>setPeriod(x)}>{x}</Button>)}</div>{notice&&<div className="mt-3 rounded-lg bg-success-soft p-3 text-sm text-success">{notice}</div>}
<section className="mt-5 overflow-hidden rounded-xl bg-card shadow-card"><div className="p-5 sm:p-6"><p className="text-xs font-semibold uppercase text-muted-foreground">Montant brut</p><p className="mt-2 text-4xl font-bold sm:text-5xl">86 540,00 <span className="text-base text-muted-foreground">MAD</span></p></div><div className="grid grid-cols-2 border-t border-border/60"><div className="p-5"><p className="text-xs text-muted-foreground">Commission</p><p className="mt-2 text-xl font-bold text-destructive">− 2 163,50 <span className="text-xs">MAD</span></p></div><div className="border-l border-border/60 p-5"><p className="text-xs text-muted-foreground">Montant net</p><p className="mt-2 text-xl font-bold text-success">84 376,50 <span className="text-xs">MAD</span></p></div></div></section>
<div className="mt-5 flex gap-2 overflow-x-auto">{source.map(x=><Button key={x} variant={filter===x?'secondary':'ghost'} size="sm" onClick={()=>setFilter(x)}>{x}</Button>)}</div>
<div className="mt-8 grid gap-5 lg:grid-cols-2"><section><h2 className="text-lg font-bold">Versements</h2><div className="mt-3 rounded-xl bg-card p-5 shadow-card"><div className="flex gap-3"><div className="grid h-10 w-10 shrink-0 place-items-center rounded-lg bg-success-soft text-success"><WalletCards className="h-5 w-5"/></div><div><p className="text-xs text-muted-foreground">Prochain versement · 28 sept.</p><p className="mt-1 text-2xl font-bold">18 420,50 MAD</p><p className="mt-1 text-xs text-muted-foreground">RIB •••• 4821 · Hebdomadaire</p></div></div><div className="my-5 h-px bg-border/70"/>{[['21 sept.','16 850,00 MAD','Versé'],['14 sept.','14 220,00 MAD','Versé'],['7 sept.','19 040,00 MAD','Échoué']].map(v=><div key={v[0]} className="flex items-center justify-between py-2"><div><p className="text-sm font-semibold">{v[0]}</p><p className="text-xs text-muted-foreground">{v[1]}</p></div><StatusBadge tone={v[2]==='Versé'?'green':'red'}>{v[2]}</StatusBadge></div>)}</div></section>
<section><div className="flex items-center justify-between"><h2 className="text-lg font-bold">Liens de paiement envoyés</h2><Send className="h-4 w-4 text-muted-foreground"/></div><div className="mt-3 overflow-hidden rounded-xl bg-card shadow-card">{[['Acompte événement','3 500,00 MAD','Payé','green'],['Location terrain · Omar','450,00 MAD','En attente','orange'],['Commande spéciale','2 100,00 MAD','Expiré','gray']].map(l=><div key={l[0]} className="grid grid-cols-[minmax(0,1fr)_auto] items-center gap-3 border-b border-border/60 p-4 last:border-0"><div className="min-w-0"><p className="truncate text-sm font-semibold">{l[0]}</p><p className="mt-1 text-base font-bold">{l[1]}</p><StatusBadge tone={l[3] as 'green'|'orange'|'gray'}>{l[2]}</StatusBadge></div><Button variant="ghost" size="icon" onClick={()=>setNotice(l[2]==='En attente'?'Lien renvoyé':'Lien annulé')} aria-label="Actions du lien"><MoreHorizontal className="h-5 w-5"/></Button></div>)}</div></section></div>
</div>}
